version: '3'
services:
  backend:
    platform: linux/amd64
    build: .
    env_file:
      - .env
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules # This is the only change for the apple silicon build