name: Build and Deploy Docker Image to GCR

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: aerobic-badge-379110
  IMAGE_NAME: thrivein-api-dev
  REGISTRY_NAME: thrivein-dev-gcr-io-eu
  TAG: aerobic-badge-379110

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up GCloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
        #   export_default_credentials: true

      - name: Configure access to Artifact Registry
        run: |
          gcloud auth configure-docker
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }} .
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}



