name: Build and Deploy Docker Image to GCR
#
on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: aerobic-badge-379110
  SERVICE_NAME: thrivein-api-dev
  REGISTRY_NAME: thrivein-dev-gcr-io-eu

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/351257798442/locations/global/workloadIdentityPools/github-wif-pool/providers/githubwif'
        service_account: '${{ secrets.RUN_SA_EMAIL }}'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"